version: '3.8'

services:

  api:
    container_name: evolution_api
    image: atendai/evolution-api:latest
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - evolution_instances:/evolution/instances
    networks:
      - shared-net
    env_file:
      - .env

# === Volumes ===
volumes:
  evolution_instances:

# === Network ===
networks:
  shared-net:
    driver: bridge
